"""Fix column name from is_verified to email_verified and remove extra columns

Revision ID: 26002970313d
Revises: 8edd4bc6532f
Create Date: 2025-12-20 22:50:07.566386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26002970313d'
down_revision: Union[str, Sequence[str], None] = '8edd4bc6532f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename is_verified column to email_verified
    op.alter_column('users', 'is_verified', new_column_name='email_verified')

    # Adjust column types for expertise fields
    op.alter_column('users', 'software_knowledge',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('users', 'hardware_knowledge',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=50),
               existing_nullable=True)

    # Drop extra columns that shouldn't exist
    op.drop_column('users', 'programming_languages')
    op.drop_column('users', 'electronics_knowledge')
    op.drop_column('users', 'robotics_knowledge')
    op.drop_column('users', 'primary_interest')
    op.drop_column('users', 'software_projects')
    op.drop_column('users', 'knowledge_level')
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the dropped columns
    op.add_column('users', sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('knowledge_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('software_projects', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('primary_interest', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('robotics_knowledge', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('electronics_knowledge', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('programming_languages', sa.TEXT(), autoincrement=False, nullable=True))

    # Rename email_verified back to is_verified
    op.alter_column('users', 'email_verified', new_column_name='is_verified')

    # Restore original column types
    op.alter_column('users', 'hardware_knowledge',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('users', 'software_knowledge',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
