"""rename auth and background columns to match spec

Revision ID: 3a938ddddd47
Revises: 26002970313d
Create Date: 2025-12-26 15:17:04.049536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a938ddddd47'
down_revision: Union[str, Sequence[str], None] = '26002970313d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename columns to match the specification
    op.alter_column('users', 'hashed_password', new_column_name='password_hash')
    op.alter_column('users', 'software_knowledge', new_column_name='software_background')
    op.alter_column('users', 'hardware_knowledge', new_column_name='hardware_background')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore original column names
    op.alter_column('users', 'password_hash', new_column_name='hashed_password')
    op.alter_column('users', 'software_background', new_column_name='software_knowledge')
    op.alter_column('users', 'hardware_background', new_column_name='hardware_knowledge')
    # ### end Alembic commands ###
