"""Add authentication and background knowledge fields to users table

Revision ID: 8edd4bc6532f
Revises: d4857f64cf56
Create Date: 2025-12-19 19:39:39.962146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8edd4bc6532f'
down_revision: Union[str, Sequence[str], None] = 'd4857f64cf56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with nullable=True first to handle existing data
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('software_knowledge', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('hardware_knowledge', sa.String(length=50), nullable=True))

    # Update existing rows with default values for hashed_password if needed
    # In a real scenario, you might want to set a default password for existing users
    # or handle them differently, but for now we'll leave hashed_password as NULL
    # and the application will handle this case.

    # If needed, make the hashed_password column non-nullable after setting values
    # op.alter_column('users', 'hashed_password', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hardware_knowledge')
    op.drop_column('users', 'software_knowledge')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
