"""add personalized_content table

Revision ID: c9ccd22d7d65
Revises: 3a938ddddd47
Create Date: 2025-12-26 15:38:47.716685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ccd22d7d65'
down_revision: Union[str, Sequence[str], None] = '3a938ddddd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update existing users to have default values for new non-nullable columns
    # This handles the case where existing users don't have password_hash or background info
    op.execute("UPDATE users SET password_hash = 'default_hash' WHERE password_hash IS NULL")
    op.execute("UPDATE users SET software_background = 'beginner' WHERE software_background IS NULL OR software_background = ''")
    op.execute("UPDATE users SET hardware_background = 'beginner' WHERE hardware_background IS NULL OR hardware_background = ''")

    # Now create the personalized_contents table
    op.create_table('personalized_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.String(length=500), nullable=False),
    sa.Column('chapter_url', sa.String(length=1000), nullable=False),
    sa.Column('original_content_hash', sa.String(length=255), nullable=False),
    sa.Column('personalized_summary', sa.Text(), nullable=False),
    sa.Column('personalization_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Now alter the columns to be NOT NULL
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'software_background',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('users', 'hardware_background',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hardware_background',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'software_background',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('personalized_contents')
    # ### end Alembic commands ###
